all scripts:
  - script.restart_https_proxy
  - script.timed_lamp
  - script.steps_timer_off
  - script.reload_config
  - script.timer_off
  - script.master_bedroom_motion_helper
  - script.update_hass
  - script.restart_ha
  - script.timed_theater_lights
  - script.occupancy
  - script.master_bedroom_motion_timer
  - script.good_night
  - script.good_morning
  - script.backup_config
  - script.theater_lights_off
  - script.notify_me
  - script.rebuild_customize
  - script.steps_timer_on
all automation:
  - automation.fan_control_off_with_temp
  - automation.fan_control_on_with_temp
  - automation.binary_turn_on_kitchen_light_when_there_is_movement
  - automation.turn_on_master_bedroom_light_when_there_is_movement
  - automation.binary_turn_off_kitchen_light_when_there_is_no_movement
  - automation.close_curtains_sunset
  - automation.curtain_open
  - automation.fan_speed_selected
  - automation.turn_porch_light_off_at_sunrise
  - automation.curtain_reset_open
  - automation.update_available_notifications
  - automation.turn_theater_lights_to_80_on_motion_if_no_activity
  - automation.porch_animation_speed
  - automation.pool_door_lights
  - automation.monitor_traffic_2
  - automation.zwave_network_is_complete
  - automation.24__minimote_button_2_pressed
  - automation.76_detect_light_between_8pm_and_5am
  - automation.radio
  - automation.turn_off_attic_light_when_door_is_closed
  - automation.log_level
  - automation.24_2_minimote_button_3_pressed
  - automation.garage_door_reset
  - automation.monitor_traffic
  - automation.holiday_led_stuff_off
  - automation.update_notification
  - automation.24_4_minimote_button_4_pressed
  - automation.24_3_minimote_button_3_held_2
  - automation.open_curtains_sunrise
  - automation.turn_holiday_led_on_at_sunset
  - automation.turn_off_master_bedroom_light_when_there_is_no_movement
  - automation.turn_off_kitchen_light_when_there_is_no_movement
  - automation.garage_entry
  - automation.24_minimote_button_1_pressed
  - automation.porch_input_effect
  - automation.update_available_notification
  - automation.notify_if_any_doors_left_open_for_10_minutes
  - automation.notify_ios_actionable_notifications
  - automation.charlie_is_away
  - automation.turn_on_kitchen_light_when_there_is_movement
  - automation.curtain_reset_close
  - automation.24_2_minimote_button_2_held
  - automation.startup_notification
  - automation.minimote_button_1_pressed
  - automation.turn_on_day_star
  - automation.turn_on_attic_light_when_door_opened
  - automation.tv_lights_and_fan_off
  - automation.sound_the_alarm
  - automation.fan_power_reset
  - automation.turn_porch_light_on_at_sunset
  - automation.silence_alarm
  - automation.set_radio_volume
  - automation.turn_front_lights_on_at_sunset
  - automation.fan_speed_selected_2
  - automation.view_lights
  - automation.turn_off_day_star
  - automation.charlie_is_home
  - automation.notify_low_battery
  - automation.front_light_off
  - automation.curtain_reset
  - automation.24_full_minimote_button_1_held
  - automation.trash_and_recycle_pickup_reminder
  - automation.24_3_minimote_button_3_held
  - automation.tv_lights_and_fan_on
